### ISSUE TITLE
The radar sensor is not functioning properly after the program is packaged

### ISSUE THREAD

**Issue by chu12345** [Field-Robotics-Japan/UnitySensors#109]
I was simulating Lidar using the 2.0b Depth Camera, and it worked fine in unity's editor mode, but when I packaged it as a windows executable, it couldn't execute, with an error message about color2depth.cs,  please help me  solve this  problem!

**Comment by Autumn60** [comment]
Thanks for raising the Issue.

It seems to simular to following issue.

https://github.com/Field-Robotics-Japan/UnitySensors/issues/64#issuecomment-1783409312 in https://github.com/Field-Robotics-Japan/UnitySensors/issues/64

**Comment by RyodoTanaka** [comment]
This Issue is duplicated and already solved.
So, I close it.
