### ISSUE TITLE
velodyne_pointcloud packageについて

### ISSUE THREAD

**Issue by 1222-takeshi** [Field-Robotics-Japan/UnitySensors#13]
最近VTCを使わせていただいて、以下のことに気がついたので報告させていただきます。

最新のvelodyne_pointcloud packageはtypeがcloud_nodeではなく、transform_nodeに変わっているようです。
こちらの変更で動作確認済みです。
各readmeを変更するだけなので、PR出すまでもないかなということでissue立てました。
確認よろしくおねがいします。
` <node pkg="velodyne_pointcloud" type="cloud_node" name="$(arg manager)">`

https://github.com/ros-drivers/velodyne/commit/f123e98cb0722b3fb1e996773ec9a9f6a6d4f57d#diff-e2094e8e5e679670f29197fb99d329f2fdcf1152304c717c11a6b68b14daa626R13

**Comment by RyodoTanaka** [comment]
こちら，修正版を作成しました！
よろしくおねがいします．

**Comment by 1222-takeshi** [comment]
すみません、修正版ってどれでしょうか？
masterブランチでは修正されていないような...

**Comment by RyodoTanaka** [comment]
@1222-takeshi 
すみません！
おっしゃるとおり，変更してませんでした...orz
すぐに変更します！

当方，ROS1 は noetic で検証しているのですが，apt で入る velodyne_pointcloud パッケージだと，Python の permission error が原因でlaunchに失敗します...orz
ローカルにソースコードを引っ張ってくれば，tag 1.6.0 以上で動作を確認できました．

このあたり，なにかご存知でしたら教えていただけると幸いです．
よろしくおねがいします！

**Comment by RyodoTanaka** [comment]
修正しました！
https://github.com/Field-Robotics-Japan/UnitySensorsROSAssets/commit/9cedd8073647507ee898830e0d7ca240f02d4f76

**Comment by 1222-takeshi** [comment]
確認しました！
対応ありがとうございます :bow: 

> 当方，ROS1 は noetic で検証しているのですが，apt で入る velodyne_pointcloud パッケージだと，Python の permission error が原因でlaunchに失敗します...orz
ローカルにソースコードを引っ張ってくれば，tag 1.6.0 以上で動作を確認できました．

こちらに関してですが、私もソースをビルドしたものを使用していたので、aptで入るパッケージの方は試していなかったです。ちょっとすぐには確認できないですが、なにかわかったら共有させていただきます :bow: 
こちらのissueはクローズします。
