### ISSUE TITLE
support for GPS?

### ISSUE THREAD

**Issue by sawan-ES** [Field-Robotics-Japan/UnitySensors#15]
Hi is there support for GPS?

**Comment by RyodoTanaka** [comment]
We plan to support GPS sensors.
But not decided the release date yet.

**Comment by sawan-ES** [comment]
Hey, Thanks for response. I got the GPS sensor working using scripts in [UnitySensors](https://github.com/Field-Robotics-Japan/UnitySensors) package. Currently I'm having issues with making the Lidar 64 channel. I'll open up a new issue for that and mark this closed. Thanks!
