### ISSUE TITLE
Velodyne wrong orientation.

### ISSUE THREAD

**Issue by argolomb** [Field-Robotics-Japan/UnitySensors#19]
Using the Velodyne LiDAR the point cloud was incorrect about orientation, maybe it's because of the different coordinate system between ROS and Unity, I try to make some changes on Rotate Lidar Scrips but without success.  A screenshot of the same view on unity was expected on Rviz but the objects appear to be mirrored or flipped. Ex. The red ball should be on the right on RVIZ but it's on left. 
![Selection_018](https://user-images.githubusercontent.com/25713412/157744128-af8b478f-32ab-4c4f-90f3-1b72aa269f0b.png)
.

**Comment by babindemers** [comment]
Change Rotate Dir to CW in the Rotate Lidar Script in the Unity Inspector window. It seems to have fixed the problem for me.

**Comment by RyodoTanaka** [comment]
@argolomb 
The solution is completely same as @babindemers wrote.

@babindemers 
Thank you for your comment !!

**Comment by RyodoTanaka** [comment]
@argolomb 
Have you notice the reply ?
I think the solution is already reviewed.
Thus, I will close this issue after this month (June 2022).

If you have more problems, please re-open it.

Best,

**Comment by argolomb** [comment]
Sorry for my late. 
@babindemers thank you.
