### ISSUE TITLE
Mirrored Velodyne cloud

### ISSUE THREAD

**Issue by robograffitti** [Field-Robotics-Japan/UnitySensors#22]
Like the picture attached the velodyne cloud seems to be mirrored
![Screenshot from 2022-07-19 13-21-12](https://user-images.githubusercontent.com/5218765/179664200-03f9d736-4f2d-43e7-8f06-5fbb44c945b9.png)
.

**Comment by RyodoTanaka** [comment]
This issue looks same as https://github.com/Field-Robotics-Japan/UnitySensorsROSAssets/issues/19 .
Please check that.

**Comment by robograffitti** [comment]
Resolved! Thanks!
