### ISSUE TITLE
Error in ROS2

### ISSUE THREAD

**Issue by lidiaxp** [Field-Robotics-Japan/UnitySensors#32]
Hey, I am using your code in my research. The last update in the code add some features but created some errors to ROS2 simulations. 

![Screenshot from 2023-07-17 00-32-35](https://github.com/Field-Robotics-Japan/UnitySensors/assets/12784079/96a5e88c-d842-4243-b354-0ef6fcd73cd6)

**Comment by Autumn60** [comment]
https://github.com/Field-Robotics-Japan/UnitySensors/pull/36

Thanks for the issue report.
Could you try this "hotfix ros2 header" or "develop" branch?
I think it has been fixed.

**Comment by lidiaxp** [comment]
Actually I am using the package adding by the git url, is it possible to set the branch in this way?

**Comment by lidiaxp** [comment]
I replaced the code with the one in "hotfix ros2 header" and replace the uint for seconds to int. Now it is working. Thank you very much.

**Comment by Autumn60** [comment]
Yes, you can download packages from a specific branch by appending "#{BRANCH_NAME}" to the URL.

Example:
・UnitySensors pkg from develop branch

`https://github.com/Field-Robotics-Japan/UnitySensors.git?path=/Assets/UnitySensors#develop`

・UnitySensorsROS pkg from develop branch

`https://github.com/Field-Robotics-Japan/UnitySensors.git?path=/Assets/UnitySensorsROS#develop`

If you've already downloaded this pkg from another branch, you don't need to remove old version.
