### ISSUE TITLE
The UNKNOWN_OBJECT_TYPE TextureToPointsJob.pixels has been deallocated. All containers must be valid when scheduling a job.

### ISSUE THREAD

**Issue by hushuaibo** [Field-Robotics-Japan/UnitySensors#33]
The UNKNOWN_OBJECT_TYPE TextureToPointsJob.pixels has been deallocated. All containers must be valid when scheduling a job.

**Comment by hushuaibo** [comment]
When I wanted to use UnitySensors, this issue occurred “The UNKNOWN_OBJECT_TYPE TextureToPointsJob.pixels has been deallocated. All containers must be valid when scheduling a job.” and LivoxMid70 was unable to hit points on my own obstacles

**Comment by Autumn60** [comment]
Thanks for the issue report.

This is a known issue, but one that is not reproducible and is difficult to fix.
If you don't mind, it would be helpful to know your system environment.

**Comment by Autumn60** [comment]
Several bugs have been fixed in https://github.com/Autumn60/UnitySensors/pull/1
Could you try "develop" branch?

**Comment by RyodoTanaka** [comment]
We need to represent @hushuaibo bug situation.
If anyone meets same error, please report it.

**Comment by Autumn60** [comment]
I have found a way to fix it, but I am currently working on other tasks and cannot submit a PR. So I will just describe how to fix it.

After calling `AsyncGPUReadback.Request()`
Call  `AsyncGPUReadback.WaitAllRequests()`
