### ISSUE TITLE
No Getter for Lidar Config

### ISSUE THREAD

**Issue by Jack17432** [Field-Robotics-Japan/UnitySensors#54]
There is no getter method for Min, max distances and other such lidar config values for the non ros sensor.

```
[SerializeField]
private float _minDistance = 0.0f;
[SerializeField]
private float _maxDistance = 100.0f;
[SerializeField]
private float _maxIntensity = 255.0f;
```

**Comment by Autumn60** [comment]
I am not aware of this issue as I never use UnitySensors without UnitySensorsROS.
Thanks for reporting the Issue.

In #59 , I added a Getter property to VelodyneSensor and LivoxSensor.
