### ISSUE TITLE
IMU acceleration is affected by scale

### ISSUE THREAD

**Issue by sgrsn** [Field-Robotics-Japan/UnitySensors#55]
In IMU calculations, Transform.InverseTransformVector is used to add gravity to acceleration, but this function is scale sensitive, so if the object's scale is changed, the acceleration values will not be calculated correctly.

If the scale is set to 1, there is no problem.
![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/23274028/843a2413-8d00-4646-a678-4ba2f5e70ab6)

If the scale is changed to 0.1, the gravity of the corresponding axis is calculated as 10 times.
![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/23274028/839c0161-c5b3-401a-a0d7-20524887e1e9)

**Comment by Autumn60** [comment]
Fixed this issue in #57.

**Comment by sgrsn** [comment]
@Autumn60 
I have confirmed another problem. InverseTransformVector has the effect of shifting the angle if the scale of each axis is different. For example, when tilted by 45°, the acceleration of the two axes does not have the same magnitude.
I think we should consider a method that does not use Transform.InverseTransformVector.
![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/23274028/5e11efb1-52b9-4ab4-b4cb-dbe2da8ac985)
![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/23274028/fe8354b9-89ad-4c8a-bad0-8f4239185987)

**Comment by RyodoTanaka** [comment]
This issue looks solved.
I close this.
