### ISSUE TITLE
Depth camera values are wrong after build.

### ISSUE THREAD

**Issue by DaiGuard** [Field-Robotics-Japan/UnitySensors#64]
# Overview

When I play in Unity, I can subscribe to the point cloud data as I expect, but I am not getting the correct point cloud that I can subscribe to from the application after I build it.

# Environment

Ubuntu 20.04
Unity 2022.3.5.f1
ROS TCP Connector: 0.7.0-preview
UnitySensors: 0.1.1
UnitySensorsROS: 0.1.1
URDF Importer: 0.5.2-preview

# Capture Image

* Play Mode
![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/26181834/5fcb4606-f455-4e39-a69b-d197c33cae02)

* After Build
![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/26181834/fa3b39a5-37b3-4e15-ac7e-013acd5e0847)

**Comment by Autumn60** [comment]
Thanks for the issue report.
We were not able to confirm the operation of the built application.

It is similar to when the depth value is inverted.

Could you try changing [line 48 of Color2Depth.shader](https://github.com/Field-Robotics-Japan/UnitySensors/blob/master/Assets/UnitySensors/Runtime/Shaders/Color2Depth.shader#L48) as follows.
~~~
float distance = length(viewPos) / _F;
~~~

**Comment by DaiGuard** [comment]
@Autumn60 

Thank you for your response.
I was trying i out right away, but the depth data is still wrong in the build application.

## Change code
![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/26181834/690be384-2fec-42d7-87a3-d48275b9653c)

## Capture image

- Play Mode
![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/26181834/14994006-f0a0-4439-856b-71405dd29c3c)

- After build
![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/26181834/4123021e-c7fb-4c5f-a780-373f6cbd37a0)

**Comment by panagelak** [comment]
@DaiGuard  @Autumn60 hello, i fix it by copying this shader 

https://github.com/Field-Robotics-Japan/UnitySensors/tree/master/Assets/UnitySensors/Runtime/Shaders 

into my project assets,

the go to Edit -> Project Settings -> Graphics and include this shader to the always included shaders.

i suppose this shader is not linked in the script but rather using a shader.find method

cheers

**Comment by RyodoTanaka** [comment]
This solution must be added to trouble shooting on README.
I will create PR.

**Comment by RyodoTanaka** [comment]
I added this discussion into README trouble shooting.
Thank you @panagelak and @Autumn60 !!
