### ISSUE TITLE
Mac os render error without psize

### ISSUE THREAD

**Issue by LiangHuangBC** [Field-Robotics-Japan/UnitySensors#65]
Running on Macos, with tons of warning:
Drawing with MeshTopology.Points, yet the vertex program 'Sprites/Default' does not have PSIZE output.

And page is messy with wrong points
<img width="1448" alt="image" src="https://github.com/Field-Robotics-Japan/UnitySensors/assets/40865875/86e9473d-6ff1-445d-a609-2ae26e5c8502">

**Comment by Autumn60** [comment]
Thanks for the Issue report.

It seems to same issue as https://github.com/keijiro/Pcx/issues/71.

There are two possible solutions at this time

(1) Set [Material] to [None] in VelodynePointsMeshGenerator.cs.

![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/37181352/ea7a23eb-f49b-42fe-8427-12f4ac3abc85)

(2) Deactivate the VelodynePointsMesh object and change the [Visualize Mode] of VelodyneVisualizer.cs, which is attached to VelodyneSensor, to [ALWAYS].

![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/37181352/870f54a4-1386-458a-b404-cb6abd6ef671)

**Comment by RyodoTanaka** [comment]
This issue looks solved.
I will close it.
If you need more discussion, please do not hesitate to re-open it.
