### ISSUE TITLE
UnitySensorROSのVelodyneMsgSerializer.csでキャストエラーが起こる。

### ISSUE THREAD

**Issue by betelgeuse931yo** [Field-Robotics-Japan/UnitySensors#66]
![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/130673246/3ed0fc1c-3572-40b0-b8c9-1b23486d7132)

添付画像のとおり、UnitySensorROSパッケージをインストール後、キャスト忘れによるエラーが発生する。

**Comment by Autumn60** [comment]
@betelgeuse931yo 
上記PRにて修正を出しています。
hotfix/ros2_headerブランチを試していただきたいです。

**Comment by RyodoTanaka** [comment]
@betelgeuse931yo 
該当PRをマージしました。
`master` ブランチで利用可能になっていますのでご確認ください。

@Autumn60 
ありがとうございました！！
