### ISSUE TITLE
LiDARの解像度設定

### ISSUE THREAD

**Issue by betelgeuse931yo** [Field-Robotics-Japan/UnitySensors#82]
LiDARセンサーのパラメータを変更する方法を教えてください。
水平解像度はAzimuth Resolutionの値を変更すれば良いのはわかりますが、垂直解像度であるZenith Anglesの要素はどのようにして決めているのでしょうか。

**Comment by Autumn60** [comment]
ZenithAngles[]は垂直角を1本ずつ指定するものです(単位は[deg])。
垂直解像度はZenithAngles[]の配列サイズで決定されます。

予め用意しているデータセット(VLP-16やVLP-32)は、製品のデータシートから角度を調べて入力しています。
