### ISSUE TITLE
Sensor data visualization issue

### ISSUE THREAD

**Issue by Kwan-Ho-Kim** [Field-Robotics-Japan/UnitySensors#85]
Thank you for developing amazing project so that we can use some sensors in Unity with ROS.
But I think there is a geometrical problem about ROS Connection.
When I tried to visualize sensor data with Unity Robotics Visualizations package, I got below data which seems like some geometrical error.

![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/112551361/447d1d7d-543d-4bd8-a310-9f1fdd510584)

Please consider revising this problem. Thank you:)

**Comment by Autumn60** [comment]
Thanks for the Issue.
We are currently working on a redesign of UnitySensors in [dev/restruct](https://github.com/Field-Robotics-Japan/UnitySensors/tree/dev/restruct) branch and the geometrical issue will be fixed accordingly.

![image](https://github.com/Field-Robotics-Japan/UnitySensors/assets/37181352/3e5466f8-5fca-486a-804e-8aa2176d1dea)
